export interface TeamMatch {
    Pool                :string,
	Fight               :string,
	Shiaijo             :string,
	NumberTareWhite     :string,
	NameTareWhite       :string,
	HansokuWhite        :string,
	IpponWhite2         :string,
	IpponWhite1         :string,
	EnchoOrHikiwake     :string,
	IpponRed1           :string,
	IpponRed2           :string,
	HansokuRed          :string,
	NumberTareRed       :string,
	NameTareRed         :string,
	FightNumber         :string,
	TeamWhite           :string,
	WinsWhite           :string,
	SetWhite            :string,
	TeamEnchoOrHikiwake :string,
	SetRed              :string,
	WinsRed             :string,
	TeamRed             :string,
	Updated             :string,
}
